// Code generated by mockery v2.7.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	models "github.com/subodhqss/test-api/models"
)

// EmployeeRepository is an autogenerated mock type for the EmployeeRepository type
type EmployeeRepository struct {
	mock.Mock
}

// AddEmployee provides a mock function with given fields: emp
func (_m *EmployeeRepository) AddEmployee(emp *models.Employee) (*models.Employee, error) {
	ret := _m.Called(emp)

	var r0 *models.Employee
	if rf, ok := ret.Get(0).(func(*models.Employee) *models.Employee); ok {
		r0 = rf(emp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Employee)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.Employee) error); ok {
		r1 = rf(emp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEmployeeInOffice provides a mock function with given fields: officeCode
func (_m *EmployeeRepository) GetEmployeeInOffice(officeCode string) (*models.Offices, error) {
	ret := _m.Called(officeCode)

	var r0 *models.Offices
	if rf, ok := ret.Get(0).(func(string) *models.Offices); ok {
		r0 = rf(officeCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Offices)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(officeCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetEmployees provides a mock function with given fields:
func (_m *EmployeeRepository) GetEmployees() ([]*models.Employee, error) {
	ret := _m.Called()

	var r0 []*models.Employee
	if rf, ok := ret.Get(0).(func() []*models.Employee); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Employee)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOneEmployeeById provides a mock function with given fields: empNo
func (_m *EmployeeRepository) GetOneEmployeeById(empNo string) (*models.Employee, error) {
	ret := _m.Called(empNo)

	var r0 *models.Employee
	if rf, ok := ret.Get(0).(func(string) *models.Employee); ok {
		r0 = rf(empNo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Employee)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(empNo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertTwoFA provides a mock function with given fields: secret
func (_m *EmployeeRepository) UpsertTwoFA(secret string) (int, error) {
	ret := _m.Called(secret)

	var r0 int
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(secret)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(secret)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
